### PR TITLE
Update ResolverChat.ts | Mutation to delete test data added.

### PR DESCRIPTION
**Pull request by malik19995**
Added a mutation to delete test data. All chats upto provided id are deleted.

### CODE REVIEW

**Review by vincenzopalazzo — APPROVED** [review]
Awesome thanks!

**Comment by vincenzopalazzo** [comment]
Ah, it is missed a `make` run on  root dir

**Comment by malik19995** [comment]
Added a new commit after running `make` on root.

**Comment by vincenzopalazzo** [comment]
Thanks!

**Pull request merged**
